// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRAkVe2A0BV56W9DaaH7OjKecX75Sp14',
    appId: '1:659770646336:web:7c3a3620fec01fd7b064a5',
    messagingSenderId: '659770646336',
    projectId: 'trash-management-c2783',
    authDomain: 'trash-management-c2783.firebaseapp.com',
    storageBucket: 'trash-management-c2783.appspot.com',
    measurementId: 'G-BE27K90Z9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6c364AuQ0_LRRH91bqHKzkjOQW6jUqw',
    appId: '1:659770646336:android:6261d0869ca09cfcb064a5',
    messagingSenderId: '659770646336',
    projectId: 'trash-management-c2783',
    storageBucket: 'trash-management-c2783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzaHCqXJz6TFiDNFWDQYi-lXodUgyh1yo',
    appId: '1:659770646336:ios:c9019dd926123982b064a5',
    messagingSenderId: '659770646336',
    projectId: 'trash-management-c2783',
    storageBucket: 'trash-management-c2783.appspot.com',
    iosClientId: '659770646336-liofhq8c5v1t6f5j4tsv06hm1f6sa893.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashManagement',
  );
}
